// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"dd408f539fcd31a90dbf977e03ac704d128fa1ea19c676b1ef50c9ead38c3d88b8594a9aefdefde96d47d324baf77cb6e68336cd2511bfa1b7518b1a7b5b8b1c"}}
];
